Updated Syntax
mdn/fetch-examples pull request #20
Opened 2022-07-01 14:00 UTC by PrajwalBorkar

Removed var and replaced with const.
Reference [issue](https://github.com/mdn/content/pull/17820#pullrequestreview-1025798386)
@teoli2003

2022-07-02 07:08 UTC, teoli2003 requested changes
As we have to edit both this page and the counterparts on mdn/content each time we want to update this, we should do all the changes in one go.

Here, in addition to `var` to `const`, I have:
- Used arrow functions for anonymous functions
- Used a literal template.

Two more things should be done (but I can't propose change to them in the GitHub UI):

1. Line 10 to 13: the comment for IE9 should be removed.
2. Another literal string should be used at line 28.

2022-07-02 07:08 UTC, teoli2003 commented on fetch-request/index.html
>      .then(function(response) {
```suggestion
    .then( (response) => {
```

2022-07-02 07:08 UTC, teoli2003 commented on fetch-request/index.html
>      .then(function(myBlob) {
```suggestion
    .then((myBlob) => {
```

2022-07-02 07:08 UTC, teoli2003 commented on fetch-request/index.html
>      .catch(function(error) {
```suggestion
    .catch((error) => {
```

2022-07-02 07:08 UTC, teoli2003 commented on fetch-request/index.html
>          document.createTextNode('Error: ' + error.message)
```suggestion
        document.createTextNode(`Error: ${error.message}`)
```

2022-07-02 07:10 UTC, teoli2003 commented
(Note that I don't write access here, so I won't be able to merge this)

2022-07-03 06:31 UTC, PrajwalBorkar commented
> As we have to edit both this page and the counterparts on mdn/content each time we want to update this, we should do all the changes in one go.
> 
> Here, in addition to `var` to `const`, I have:
> 
> * Used arrow functions instead of anonymous functions.
> * Used a literal template instead of the concatenation operator.
> 
> Two more things should be done (but I can't propose changes to them in the GitHub UI):
> 
> 1. Line 10 to 13: the comment for IE9 should be removed.
> 2. Another literal string should be used at line 28.

Made the changes 👍

2022-07-03 07:08 UTC, teoli2003 commented on fetch-request/index.html
> +    .then( (response) => {
```suggestion
    .then((response) => {
```

2022-07-03 07:10 UTC, teoli2003 commented
A last typo and this is ready. Pinging @schalkneethling or @rumyra as I don't have the rights to review/merge here.

2022-07-03 10:21 UTC, schalkneethling approved these changes
Thank you, @PrajwalBorkar and welcome to the community 🎉

2022-07-03 10:25 UTC, merged